language: "python"

python:
    - 2.7
    - 3.3
    - pypy

virtualenv:
    system_site_packages: true

before_install:
    - pip freeze
    - sudo apt-get update -qq
    - sudo apt-get install -qq libatlas-base-dev liblapack-dev gfortran cython
      # due to a bug in matplotlib, numpy and matplotlib cannot be installed
      # together via requirements.txt, numpy has te be installed first
      # http://stackoverflow.com/questions/11797688/matplotlib-requirements-with-pip-install-in-virtualenv
    - pip install numpy

install:
    - pip install -r requirements.txt --use-mirrors

matrix:
    allow_failures:
        - python: 3.3
        - python: pypy

script: ./testall.sh

