language: "python"

python:
    - 2.7
    - 3.3
    - pypy

virtualenv:
    system_site_packages: true

before_install:
    - sudo apt-get update
    - sudo apt-get install python-numpy python3-numpy
    - sudo apt-get install python-scipy python3-scipy
    - sudo apt-get install python-matplotlib
    - sudo apt-get install python-sklearn

install:
     - pip install -r requirements.txt --use-mirrors

matrix:
    allow_failures:
        - python: 3.3
        - python: pypy

script: ./testall.sh

