language: "python"

python:
  - "2.7"
  - "3.3"

install: 
# numpy build-dependencies
  - "sudo apt-get install python-all-dev python3-all-dev python-support gfortran libblas-dev liblapack-dev"
# numpy dependencdies
  - "sudo apt-get install libblas3gf liblapack3gf libatlas3gf-base"
# scipy build-dependencies
  - "sudo apt-get install python-all-dev python3-all-dev cython gfortran libblas-dev liblapack-dev libatlas-base-dev"
# scipy dependencies
  - "sudo apt-get install libblas3gf liblapack3gf libatlas3gf-base"
  - "pip install -r requirements.txt --use-mirrors"

script: "./testall.sh"

