language: "python"
python:
  - "2.7"
  - "3.3"
install: 
# numpy fails to build in the travis environment
  - "apt-get install python-numpy"
  - "pip install -r requirements.txt --use-mirrors"
script: "./testall"

