language: "python"

python:
  - "2.7"
  - "3.3"

virtualenv:
  system_site_packages: true

install: 
# numpy fails to build in the travis environment
  - "sudo apt-get install python-numpy"
  - "pip install -r requirements.txt --use-mirrors"

script: "./testall"

